### PR TITLE
Replaced logging module with a package logger variable

### PR DESCRIPTION
**Pull request by VasLem**
Related to #49

### CODE REVIEW

**Comment by EpigeneMax** [comment]
Thank you very much for this PR.

Overall the changes are OK, yet some tests fail to pass.
@VasLem would you have time to amend your changes to pass the tests?
I would also recommend to sync with the latest changes on `master`.

**Comment by VasLem** [comment]
Hi Max, sorry for being so late, I had some matters to cater for. I think I fixed the issue and updated the code to the upstream.

**Comment by EpigeneMax** [comment]
Great to hear from you :)
I pushed a commit to adjust some tests: they were checking that a warning was raised, but after thinking about it, it makes more sense to check for a warning-level log message.
Also reformated the code using the latest version of `ruff`.

Thanks a lot for your contribution 🙏

**Review by EpigeneMax — APPROVED** [review]
All good.
Cheers to our new contributor 👏

**Pull request merged**
